get http://localhost:4000/user-api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5JS0tJIiwiaWF0IjoxNzIxOTcwOTY5LCJleHAiOjE3MjE5NzQ1Njl9.4o9dLL1vHzS1FaRANO1jaxr1ZqRlKz6QIgg6prV8khg


###
get http://localhost:4000/user-api/users/CSE100001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNTRTEwMDAwMSIsImlhdCI6MTcyNTE2MjgyOSwiZXhwIjoxNzI1MTY2NDI5fQ.6lMHen1uSHbmuZJgEfxHZ4IoXokNOQYbg2eUQOmh_UU


###
post http://localhost:4000/user-api/user
Content-Type: application/json

{
    "username":"",
    "name":"",
    "email":"",
    "profile_pic":"",
    "password":""
}

###
post http://localhost:4000/user-api/login
Content-Type: application/json

{
    
    "username":"CSE100001",
    "password":"Pvpsit@123"
   
}


###
post http://localhost:4000/user-api/book-slot
Content-Type: application/json

{
    
    "roomNo": "*", 
      "date": "2024-09-11",
      "timeSlots": [
        "09:00 am - 10:00 am",
        "12:00 pm - 01:00 pm",
        "10:00 am - 11:00 am",
        "11:00 am - 12:00 pm"
      ]
   
}


###
get  http://localhost:4000/user-api/bookedSlots


###
delete http://localhost:4000/user-api/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hZGh1IiwiaWF0IjoxNzIwODYwNjkxLCJleHAiOjE3MjA4NjQyOTF9.rq1To5-djRFwJniKaHE7W40V3bpGgPuwbsCe283vxSk



